// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLRy8qalJmrWH79AoR0PJ5iIUSODkhUsI',
    appId: '1:825487632862:web:ac66328a85a3a946f4154f',
    messagingSenderId: '825487632862',
    projectId: 'agc-mockup',
    authDomain: 'agc-mockup.firebaseapp.com',
    storageBucket: 'agc-mockup.appspot.com',
    measurementId: 'G-4QH0ZL0GYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdps4pbheUmRLEl-00cH8Qv7N-tdgH_ws',
    appId: '1:825487632862:android:c1304242fb91bb62f4154f',
    messagingSenderId: '825487632862',
    projectId: 'agc-mockup',
    storageBucket: 'agc-mockup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCd6i0KFdIt9y2b-njsvG3l5kbwvf2-8Cg',
    appId: '1:825487632862:ios:c7ff0015fbac22b7f4154f',
    messagingSenderId: '825487632862',
    projectId: 'agc-mockup',
    storageBucket: 'agc-mockup.appspot.com',
    iosClientId: '825487632862-81n2r78s5hn4l37tjt14o57atvl33oie.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAgcMockup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCd6i0KFdIt9y2b-njsvG3l5kbwvf2-8Cg',
    appId: '1:825487632862:ios:c7ff0015fbac22b7f4154f',
    messagingSenderId: '825487632862',
    projectId: 'agc-mockup',
    storageBucket: 'agc-mockup.appspot.com',
    iosClientId: '825487632862-81n2r78s5hn4l37tjt14o57atvl33oie.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAgcMockup',
  );
}
